version: '3'
services:
  mongo:
    image: mongo
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
      - MONGO_INITDB_ROOT_PASSWORD=123456 
      - MONGO_INITDB_DATABASE=db_js 
    ports:
      - 27017
    networks:
      - projeto_php
  node:
    image: node
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 80:3000
    networks:
      - projeto_php
    entrypoint: "npm start"
networks:
  projeto_php:
    driver: bridge  
