version: '3'
services:
  mongo:
    image: mongo
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
      - MONGO_INITDB_ROOT_PASSWORD=123456 
      - MONGO_INITDB_DATABASE=db_js 
    ports:
      - 27017
    networks:
      - net_api
  node:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks:
      - net_api
    entrypoint: "npm start"
networks:
  net_api:
    driver: bridge  